//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/committerpb/auth.proto

package committerpb

import (
	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizeRequest contains a signed envelope with the client's MSP identity.
type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signed_envelope contains the client's MSP identity and signature.
	// The envelope payload should contain the client's serialized identity
	// in the SignatureHeader.Creator field.
	SignedEnvelope *common.Envelope `protobuf:"bytes,1,opt,name=signed_envelope,json=signedEnvelope,proto3" json:"signed_envelope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_api_committerpb_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_api_committerpb_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetSignedEnvelope() *common.Envelope {
	if x != nil {
		return x.SignedEnvelope
	}
	return nil
}

// AuthorizeResponse indicates whether authorization succeeded.
type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the authorization was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the authorization result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// msp_id is the MSP identifier of the authenticated identity.
	MspId string `protobuf:"bytes,3,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	// config_sequence is the channel configuration sequence at authentication time.
	ConfigSequence uint64 `protobuf:"varint,4,opt,name=config_sequence,json=configSequence,proto3" json:"config_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_api_committerpb_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_api_committerpb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthorizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthorizeResponse) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (x *AuthorizeResponse) GetConfigSequence() uint64 {
	if x != nil {
		return x.ConfigSequence
	}
	return 0
}

var File_api_committerpb_auth_proto protoreflect.FileDescriptor

const file_api_committerpb_auth_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/committerpb/auth.proto\x12\tservicepb\x1a\x13common/common.proto\"M\n" +
	"\x10AuthorizeRequest\x129\n" +
	"\x0fsigned_envelope\x18\x01 \x01(\v2\x10.common.EnvelopeR\x0esignedEnvelope\"\x87\x01\n" +
	"\x11AuthorizeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06msp_id\x18\x03 \x01(\tR\x05mspId\x12'\n" +
	"\x0fconfig_sequence\x18\x04 \x01(\x04R\x0econfigSequence2U\n" +
	"\vAuthService\x12F\n" +
	"\tAuthorize\x12\x1b.servicepb.AuthorizeRequest\x1a\x1c.servicepb.AuthorizeResponseB8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_auth_proto_rawDescOnce sync.Once
	file_api_committerpb_auth_proto_rawDescData []byte
)

func file_api_committerpb_auth_proto_rawDescGZIP() []byte {
	file_api_committerpb_auth_proto_rawDescOnce.Do(func() {
		file_api_committerpb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_auth_proto_rawDesc), len(file_api_committerpb_auth_proto_rawDesc)))
	})
	return file_api_committerpb_auth_proto_rawDescData
}

var file_api_committerpb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_committerpb_auth_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: servicepb.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 1: servicepb.AuthorizeResponse
	(*common.Envelope)(nil),   // 2: common.Envelope
}
var file_api_committerpb_auth_proto_depIdxs = []int32{
	2, // 0: servicepb.AuthorizeRequest.signed_envelope:type_name -> common.Envelope
	0, // 1: servicepb.AuthService.Authorize:input_type -> servicepb.AuthorizeRequest
	1, // 2: servicepb.AuthService.Authorize:output_type -> servicepb.AuthorizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_committerpb_auth_proto_init() }
func file_api_committerpb_auth_proto_init() {
	if File_api_committerpb_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_auth_proto_rawDesc), len(file_api_committerpb_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_committerpb_auth_proto_goTypes,
		DependencyIndexes: file_api_committerpb_auth_proto_depIdxs,
		MessageInfos:      file_api_committerpb_auth_proto_msgTypes,
	}.Build()
	File_api_committerpb_auth_proto = out.File
	file_api_committerpb_auth_proto_goTypes = nil
	file_api_committerpb_auth_proto_depIdxs = nil
}
